services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./src:/usr/local/app/src  
    environment:
      MONGO_URI: mongodb://shorryah:mongo123@mongodb:27017/user_db?authSource=admin
    networks:
      - appnet

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: shorryah
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: user_db
    volumes:
      - mongodata:/data/db
    networks:
      - appnet

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - appnet

volumes:
  mongodata:
  ollama_data:

networks:
  appnet:
    driver: bridge
